# This GitHub Actions workflow is designed to deploy a specific folder from the main branch to the gh-pages branch.
# 
# Step-by-step explanation:
# 1. The workflow is triggered by a push event to the main branch.
# 2. The job named 'deploy' runs on the latest version of Ubuntu.
# 3. The first step checks out the repository using the actions/checkout@v2 action.
# 4. The second step configures Git with a username and email for the GitHub Actions bot.
# 5. The workflow fetches the gh-pages branch from the remote repository.
# 6. It then checks out the gh-pages branch.
# 7. The specified folder from the main branch is copied to the root of the gh-pages branch.
# 8. All changes are staged for commit.
# 9. A commit is created with the message "Deploy to gh-pages".
# 10. Finally, the changes are pushed to the gh-pages branch on the remote repository.

name: Deploy to gh-pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Fetch gh-pages branch
              run: git fetch origin gh-pages

            - name: Checkout gh-pages branch
              run: git checkout gh-pages

            - name: Copy files
              run: | 
                cp -r docs/_build/doctrees .
                cp -r docs/_build/html/* .

            - name: Commit and push changes
              run: |
                git add .
                git commit -m "Deploy to gh-pages"
                git push origin gh-pages