ocname: Deploy to gh-pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Git
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Fetch gh-pages branch
              run: git fetch origin gh-pages

            - name: Checkout gh-pages branch
              run: git checkout gh-pages

            - name: Copy files
              run: | 
                cp -r docs/_build/doctrees .
                cp -r docs/_build/html/* .

            - name: Commit and push changes
              run: |
                git add .
                git commit -m "Deploy to gh-pages"
                git push origin gh-pages